
kafkaDemoService:
  serviceAccountName: kafka-demo-app-sasl-scram-serviceaccount
  replicaCount: 3
  image:
    image: garystafford/kafka-demo-service:1.2.2-scram
    pullPolicy: IfNotPresent
    ports:
      containerPort: 8080