
kafkaDemoService:
  serviceAccountName: kafka-demo-app-sasl-scram-serviceaccount
  replicaCount: 2
  image:
    image: garystafford/kafka-demo-service:1.1.0-scram
    pullPolicy: IfNotPresent
    ports:
      containerPort: 8080